id: P002942
initial_creation_type: ocr
source_metadata:
  id: bdr:W2CZ8024
  title: ཐོས་གྲོལ་གྱི་འགྲེལ་བཤད་དང་བསྙེན་ཡིག་མཐའ་དཔྱད་ཕྱོགས་བསྒྲིགས་ལེགས་བཤད་ནོར་བུའི་ཐང་མ།
  author: ''
  volumes:
    4a7d3c11326a4582bc8f11addcafe562:
      image_group_id: I1KG12441
      title: ''
      volume_number: 1
      total_pages: 608
      base_file: v001.txt
