id: I002F7CB9
legacy_id: P002942
ocr_import_info:
  bdrc_scan_id: W2CZ8024
  source: bdrc
  ocr_info:
    timestamp: '2020-03-22T01:52:29'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-02T15:45:21.017916+00:00'
last_modified: 2022-09-02 23:46:28.681079
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W2CZ8024
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW2CZ8024
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ཐོས་གྲོལ་གྱི་འགྲེལ་བཤད་དང་བསྙེན་ཡིག་མཐའ་དཔྱད་ཕྱོགས་བསྒྲིགས་ལེགས་བཤད་ནོར་བུའི་ཐང་མ།
statistics:
  ocr_word_mean_confidence_index: 0.9304062677212571
  ocr_word_median_confidence_index: 0.9800000190734863
quality: null
bases:
  I1KG12441:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG12441
      total_pages: 608
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG12441.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9304062677212571
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
