id: I002F7CB9
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T01:56:18+00:00'
last_modified: '2022-06-07T16:22:42.058488+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W2CZ8024
  title: ཐོས་གྲོལ་གྱི་འགྲེལ་བཤད་དང་བསྙེན་ཡིག་མཐའ་དཔྱད་ཕྱོགས་བསྒྲིགས་ལེགས་བཤད་ནོར་བུའི་ཐང་མ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    FED2:
      image_group_id: I1KG12441
      title: ''
      total_pages: 608
      order: 1
      base_file: FED2.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
